[package]
name = "vmid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vmid"
path = "src/main.rs"

[lib]
name = "vmid"
path = "src/lib.rs"

[dependencies]
cursive = "0.16"
rand = "0.8.4"